[package]
name = "comfy-wars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#comfy = {path = "/tmp/comfy/comfy"}
#comfy = {git = "https://github.com/darthdeus/comfy"}
comfy = "0.1.1"
